### ISSUE TITLE
How to change the language

### ISSUE THREAD

**Issue by TheusStremens** [bpeel/pucxobot#12]
Hi, first of all, thanks for the incredibly nice and fun bot, it's a wonderful tool, especially in these quarantine times. 

My doubt is about how to change the language? I saw some translations already inside the repo, but I'm not familiar with compile/edit/adding bots.

If you want to add a new feature for people that don't know about programming, my suggestion is a `/config` feature that allows the user to change the language inside the chat with the bot.

Thanks in advance.

**Comment by bpeel** [comment]
Hi. For the moment there is no way to change the language of the bot. Instead there is an entirely separate bot for each language. The current ones that I run are:

English – [@bluffingbot](https://t.me/bluffingbot)
Portuguese – [@blefarbot](https://t.me/blefarbot)
French – [@complotbot](https://t.me/complotbot)
Esperanto – [@pucxobot](https://t.me/pucxobot)

Yes, it sounds like a good idea to add a `/config` command. If the program ends up with a lot more translations I’ll eventually hit a limit for how many bots I can have so I’ll have to take a different approach.

Thanks for the suggestion.
