### ISSUE TITLE
Users can anonymously spam the group by clicking on the start game buttons

### ISSUE THREAD

**Issue by bpeel** [bpeel/pucxobot#15]
When the bot asks which game the player wants to start, the message never gets deleted and people can keep clicking on them. The bot then replies without revealing who clicked it so they can anonymously spam the group with annoying messages.

Reported by @Sawada on Telegram. They also suggest:

> perhaps add a check for existing user on click
> if user is already in game 
> dont reply but show a "toast popup" saying "you are already in game"

**Comment by TsunayoshiSawada** [comment]
Also consider revising any existing buttons that have the reply function like this, consider switching it with a toast popup instead.
